### ISSUE TITLE
Publish Stone as a GitHub Action

### ISSUE THREAD

**Issue by afflom** [UOR-Foundation/Stone#21]
## Overview
Create and publish a GitHub Action for Stone to allow seamless integration into GitHub workflows.

## Requirements
- Create action.yml file with proper metadata
- Implement the action using JavaScript or Docker
- Set up CI/CD workflow for testing the action
- Publish the action to the GitHub Marketplace
- Add proper inputs and outputs in the action definition
- Create comprehensive documentation with examples
- Version the action appropriately
- Add usage examples to README

## Implementation Steps
1. Design the action interface (inputs/outputs)
2. Create the action.yml file
3. Implement the action in JavaScript or as a Docker container
4. Write tests for the action
5. Set up GitHub workflow for testing the action
6. Document the action with examples
7. Publish to the GitHub Marketplace
8. Create a release with semantic versioning

## Success Criteria
- Action is published to GitHub Marketplace
- Action can be used in workflows with clear documentation
- Action is properly versioned
- Example workflows demonstrate common use cases
- Action passes all tests and has good test coverage
- Documentation is clear and comprehensive

## Example Usage to Document
```yaml
name: Stone Workflow
on:
  issues:
    types: [opened, labeled]

jobs:
  stone-process:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, "stone")
    steps:
      - uses: actions/checkout@v3
      - name: Run Stone Process
        uses: UOR-Foundation/stone@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
```
